name: CI

on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
  schedule:
    # at 00:00 on every 3rd day-of-month.
    - cron: '0 0 */3 * *'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Login to ghcr.io
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build the Docker image
        run: |
          docker build \
            --tag ghcr.io/bots-house/docker-telegram-bot-api:latest \
            .

      - name: Push image to GitHub Packages
        run: |
          docker push ghcr.io/bots-house/docker-telegram-bot-api:latest