name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Login to ghcr.io
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: |
          docker build \
            --tag ghcr.io/bots-house/docker-telegram-bot-api:latest \
            .

      - name: Push image to GitHub Packages
        run: |
          docker push ghcr.io/bots-house/docker-telegram-bot-api:latest